name: "Deploy to AWS"

on:
  workflow_run:
    workflows: ["01 Build and Deploy Site"]
    types:
      - completed
  workflow_dispatch:

jobs:
  preflight:
    name: "Preflight Check"
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check.outputs.ok }}
    steps:
      - id: check
        run: |
          if [[ -z "${{ secrets.AWS_S3_BUCKET }}" || -z "${{ secrets.AWS_ACCESS_KEY_ID }}" || -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then
            echo ":information_source: No site configured" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "To deploy on AWS, you need the `AWS_S3_BUCKET`, `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY` secrets set up" >> $GITHUB_STEP_SUMMARY
          else
            echo "::set-output name=folder::"$(sed -E 's^.+/(.+)^\1^' <<< ${{ github.repository }})
            echo "::set-output name=ok::true"
          fi
    
  full-build:
    name: "Deploy to AWS"
    needs: [preflight]
    if: ${{ needs.preflight.outputs.ok }}
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout folder"
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'source'

      - name: "Deploy to Bucket"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'source'
          DEST_DIR: ${{ needs.preflight.outputs.folder }}
